### ISSUE TITLE
Any chance for a .hex file for your stages alt firmware?

### ISSUE THREAD

**Issue by riverbasin** [qiemem/eurorack#61]
Hello Qiemem,

I am have no luck with updating via the .wav file. Any chance you have .hex files of the firmware?

Also no luck with a fresh build, though I have built many MI firmwares on my Mac M1 using a local copy of the same arm-4.8.3 as for the Vagrant workspace. I also tried ArmGNUToolchain Rev13.1 you suggested with no luck. In both cases I'm getting a warning that is quitting the build and I am not savvy enough to chase it down. For what it's worth I pasted the warning below - not sure if it's related to your updates to the code base or not, though it seems to be a compiler problem on my end.

Thanks, warning message follows:

In file included from ./stages/chain_state.h:37:0,
                 from stages/chain_state.cc:29:
./stages/segment_generator.h:199:65: error: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [-Werror]
   
const int kPllCountdown = static_cast<int>(kSampleRate * 0.25f);
                                                                                                            ^
cc1plus: all warnings being treated as errors

**Comment by qiemem** [comment]
Here you go! [stages-bipolar-v1.3.0.zip](https://github.com/user-attachments/files/18335545/stages-bipolar-v1.3.0.zip)

Note I have not tested the hex (my programming is stashed somewhere... I almost always just use the wav files TBH) but should work okay.

> Also no luck with a fresh build, though I have built many MI firmwares on my Mac M1 using a local copy of the same arm-4.8.3 as for the Vagrant workspace. I also tried ArmGNUToolchain Rev13.1 you suggested with no luck.

I use 13.2rev1. That's strange though: it should be using `-std=c++11`. Do you mind copying and pasting the build command you're using and the full resulting output?

**Comment by riverbasin** [comment]
Qiemem - thanks so much for the .hex file.  Alas, it seemed to flash okay, but the module sort of just sat there with all of the LEDs along top orange and it was unresponsive. Darn. Using the .wav file has appeal of course given it's seeming simplicity, but I just go round and round gain staging in a variety of ways and just can't get the update to finish with that method. I get the flashing light sequence along the sliders, but inevitably all of the top row LEDs will blink red after a few seconds.

In my attempts to build the alt firmware from source, I copied your "stages" directory into a local copy of the "eurorack" directory from the MI git on my machine where I work from. Below see two sets of error output from the make call I made from the eurorack directory, one using arm-none-eabi_4.8.3 and one using arm-none-eabi_13.2Rel1.  In each case I copied the make call I executed along with the function call before that prompted the exit with an error.

NB, I can build the stock stages with arm-none-eabi_4.8.3
NB, when I attempted to build from a local copy of the eurorack-1.3.0 directory, it failed because the stmlib directory is empty.

Best

# using arm-gnu-toolchain-4.8.3 (e.g., same as mutable dev environment)

TOOLCHAIN_PATH=/mutableSandbox/arm-4.8.3/ make -f stages/makefile 

/mutableSandbox/arm-4.8.3/bin/arm-none-eabi-g++ -c -g -O2 -Wall -Werror -Wno-unused-local-typedefs -Wno-strict-aliasing -fasm -finline -finline-functions-called-once -fdata-sections -ffunction-sections -fshort-enums -fno-move-loop-invariants -fno-unwind-tables -I. -DGCC_ARMCM4 -DSTM32F37X -DARM_MATH_CM4 -D__FPU_PRESENT -DAPPLICATION  -DF_CPU=72000000L -DF_CRYSTAL=8000000L -DHSE_VALUE=8000000L -DUSE_STDPERIPH_DRIVER -DSYSCLK_FREQ_72MHz=72000000L -Istmlib/third_party/STM -Istmlib/third_party/STM/CMSIS/CM3_f37x -Istmlib/third_party/STM/CMSIS/CM3_f37x/startup/gcc -Istmlib/third_party/STM/STM32F37x_StdPeriph_Driver/inc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb-interwork -funroll-loops --specs=nano.specs -fno-exceptions -fno-rtti stages/braids_quantizer.cc -o build/stages/braids_quantizer.o
/Users/byronamerson/Documents/audioElectronics/mutableSandbox/arm-4.8.3/bin/arm-none-eabi-g++ -c -g -O2 -Wall -Werror -Wno-unused-local-typedefs -Wno-strict-aliasing -fasm -finline -finline-functions-called-once -fdata-sections -ffunction-sections -fshort-enums -fno-move-loop-invariants -fno-unwind-tables -I. -DGCC_ARMCM4 -DSTM32F37X -DARM_MATH_CM4 -D__FPU_PRESENT -DAPPLICATION  -DF_CPU=72000000L -DF_CRYSTAL=8000000L -DHSE_VALUE=8000000L -DUSE_STDPERIPH_DRIVER -DSYSCLK_FREQ_72MHz=72000000L -Istmlib/third_party/STM -Istmlib/third_party/STM/CMSIS/CM3_f37x -Istmlib/third_party/STM/CMSIS/CM3_f37x/startup/gcc -Istmlib/third_party/STM/STM32F37x_StdPeriph_Driver/inc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb-interwork -funroll-loops --specs=nano.specs -fno-exceptions -fno-rtti stages/chain_state.cc -o build/stages/chain_state.o
In file included from ./stages/chain_state.h:37:0,
                 from stages/chain_state.cc:29:
./stages/segment_generator.h:199:65: error: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [-Werror]
   const int kPllCountdown = static_cast<int>(kSampleRate * 0.25f);
                                                                 ^
cc1plus: all warnings being treated as errors
make: *** [stmlib/makefile.inc:285: build/stages/chain_state.o] Error 1


# using arm-gnu-toolchain-13.2.rel1

TOOLCHAIN_PATH=/mutableSandbox/arm-gnu-toolchain-13.2.rel1-darwin-arm64-arm-none-eabi/ make -f stages/makefile

/mutableSandbox/arm-gnu-toolchain-13.2.rel1-darwin-arm64-arm-none-eabi/bin/arm-none-eabi-g++ -c -g -O2 -Wall -Werror -Wno-unused-local-typedefs -Wno-strict-aliasing -fasm -finline -finline-functions-called-once -fdata-sections -ffunction-sections -fshort-enums -fno-move-loop-invariants -fno-unwind-tables -I. -DGCC_ARMCM4 -DSTM32F37X -DARM_MATH_CM4 -D__FPU_PRESENT -DAPPLICATION  -DF_CPU=72000000L -DF_CRYSTAL=8000000L -DHSE_VALUE=8000000L -DUSE_STDPERIPH_DRIVER -DSYSCLK_FREQ_72MHz=72000000L -Istmlib/third_party/STM -Istmlib/third_party/STM/CMSIS/CM3_f37x -Istmlib/third_party/STM/CMSIS/CM3_f37x/startup/gcc -Istmlib/third_party/STM/STM32F37x_StdPeriph_Driver/inc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb-interwork -funroll-loops --specs=nano.specs -fno-exceptions -fno-rtti stages/braids_quantizer.cc -o build/stages/braids_quantizer.o
/Users/byronamerson/Documents/audioElectronics/mutableSandbox/arm-gnu-toolchain-13.2.rel1-darwin-arm64-arm-none-eabi/bin/arm-none-eabi-g++ -c -g -O2 -Wall -Werror -Wno-unused-local-typedefs -Wno-strict-aliasing -fasm -finline -finline-functions-called-once -fdata-sections -ffunction-sections -fshort-enums -fno-move-loop-invariants -fno-unwind-tables -I. -DGCC_ARMCM4 -DSTM32F37X -DARM_MATH_CM4 -D__FPU_PRESENT -DAPPLICATION  -DF_CPU=72000000L -DF_CRYSTAL=8000000L -DHSE_VALUE=8000000L -DUSE_STDPERIPH_DRIVER -DSYSCLK_FREQ_72MHz=72000000L -Istmlib/third_party/STM -Istmlib/third_party/STM/CMSIS/CM3_f37x -Istmlib/third_party/STM/CMSIS/CM3_f37x/startup/gcc -Istmlib/third_party/STM/STM32F37x_StdPeriph_Driver/inc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb-interwork -funroll-loops --specs=nano.specs -fno-exceptions -fno-rtti stages/chain_state.cc -o build/stages/chain_state.o
In file included from stmlib/third_party/STM/CMSIS/CM3_f37x/core_cm4.h:147,
                 from stmlib/third_party/STM/CMSIS/CM3_f37x/stm32f37x.h:239,
                 from stmlib/third_party/STM/STM32F37x_StdPeriph_Driver/inc/stm32f37x_adc.h:38,
                 from stmlib/third_party/STM/stm32f37x_conf.h:34,
                 from ./stmlib/system/page_storage.h:48,
                 from ./stmlib/system/storage.h:38,
                 from ./stages/settings.h:33,
                 from ./stages/chain_state.h:33,
                 from stages/chain_state.cc:29:
stmlib/third_party/STM/CMSIS/CM3_f37x/core_cmFunc.h: In function 'uint32_t __get_PSP()':
stmlib/third_party/STM/CMSIS/CM3_f37x/core_cmFunc.h:412:21: error: ISO C++17 does not allow 'register' storage class specifier [-Werror=register]
  412 |   register uint32_t result;
      |                     ^~~~~~
stmlib/third_party/STM/CMSIS/CM3_f37x/core_cmFunc.h: In function 'uint32_t __get_MSP()':
stmlib/third_party/STM/CMSIS/CM3_f37x/core_cmFunc.h:439:21: error: ISO C++17 does not allow 'register' storage class specifier [-Werror=register]
  439 |   register uint32_t result;
      |                     ^~~~~~
cc1plus: all warnings being treated as errors
make: *** [stmlib/makefile.inc:285: build/stages/chain_state.o] Error 1

**Comment by qiemem** [comment]
Ah shit I'm so sorry, it's been a while since I've worked on this. I forgot to include the bootloader in the hex. Here's the combo bootload and firmware, both bin and hex
[stages_bootloader_combo_bipolar_v1.3.0.zip](https://github.com/user-attachments/files/18350061/stages_bootloader_combo_bipolar_v1.3.0.zip). Warning: I think the last time I did a jtag upload was when I was still compiling with 4.8.3 so I have not tested the bootloader compiled with 13.2. When I did use jtag, I also used the upload_combo_jtag makefile target, so you might want to reference that if you're not already. If it's still not working, it might be a good idea to go back to the factory image and build with the standard procedure before we keep troubleshooting, just to get things back in a working state.

Now, for the compilation errors, I forgot I forked stmlib to get it working with 13.2: https://github.com/qiemem/stmlib. The changes are minor. Specifically, you need to add `-std=c++11` to `CPPFLAGS`: https://github.com/qiemem/stmlib/commit/7937b83591f2531e9608e4f995f7c4f9802bfe1a#diff-827803e7c08790d4c75b912ac9a0d1f5309a8a03f80186cf7ad6d3fbdcd78eddR226

> Qiemem - thanks so much for the .hex file. Alas, it seemed to flash okay, but the module sort of just sat there with all of the LEDs along top orange and it was unresponsive. Darn. Using the .wav file has appeal of course given it's seeming simplicity, but I just go round and round gain staging in a variety of ways and just can't get the update to finish with that method. I get the flashing light sequence along the sliders, but inevitably all of the top-row LEDs will blink red after a few seconds.

What state are the top LEDs in before you start getting the red flashing? You've probably been through this, but just to cover our bases: What generally works for folks is to go straight from laptop or phone to the module. Make sure you're playing at 48kHz, not 44.1. Have the volume on the source device at full. Start with the rightmost slider halfway up. I would *not* use a mixer or amp or any other gain staging between the source device and the module. If you prefer, I am happy to try to get this route working for you.

**Comment by riverbasin** [comment]
Success! I added `-std=c++11` to `CPPFLAGS` in my local copy of makefile.inc in stmlib and it compiled and flashed successfully. Nice - I would never have figured that out. Just for kicks I successfully flashed the binary version of stages_bootloader_combo you sent along using (I have a local copy of openocd scripts):

> `openocd -s /mutableSandbox/eurorack/scripts/ -f interface/stlink.cfg -f target/stm32f3x.cfg -c "init" -c "halt" -c "sleep 200" -c "flash erase_address 0x08000000 32768" -c "reset halt" -c "flash write_image erase build/stages/stages_bootloader_combo.bin 0x08000000"-c "verify_image build/stages/stages_bootloader_combo.bin 0x08000000" -c "sleep 200" -c "reset run" -c "shutdown"`

Thank so much for your time and effort on this. I'm looking forward to checking out the alt firmware.
